import {Trophy,CalendarDays,ClipboardList,WalletCards,PackageCheck,Plus,FilePlus,HandCoins} from 'lucide-react';
import {LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,PieChart,Pie,Cell} from 'recharts';
import {Card,StatCard,PanelTitle,Badge} from '../components/UI'; import {events} from '../data';
const chart=[{m:'Dec',p:22,e:14},{m:'Jan',p:35,e:23},{m:'Feb',p:30,e:28},{m:'Mar',p:57,e:31},{m:'Apr',p:43,e:27},{m:'May',p:78,e:54}]; const pie=[{v:66,c:'#16b7aa'},{v:19,c:'#f2ae31'},{v:10,c:'#2478d4'},{v:5,c:'#ef5d69'}];
export default function Dashboard(){return <>
 <div className="hero"><div className="bubble b1"/><div className="bubble b2"/><div className="hero-copy"><Badge>SPORTS OPERATIONS</Badge><p>Welcome back,</p><h1>Make today a winning day! 🏆</h1><span>Manage programs, activities, finance, inventory and teams in one integrated platform.</span></div><div className="hero-time"><small>Sunday, 23 August 2026</small><b>22:25</b><span>WIB</span></div><div className="swimmer">🏊</div></div>
 <div className="stats-grid"><StatCard icon={<Trophy/>} title="Total Active Programs" value="32" trend="12%"/><StatCard icon={<CalendarDays/>} title="Events Running" value="8" trend="14%" color="green"/><StatCard icon={<ClipboardList/>} title="Pending Tasks" value="24" trend="8%" down color="orange"/><StatCard icon={<WalletCards/>} title="Budget Utilization" value="68.4%" color="purple"/><StatCard icon={<PackageCheck/>} title="Inventory Status" value="Good" trend="92% ready" color="green"/></div>
 <div className="dashboard-grid">
  <Card className="analytics"><PanelTitle title="Sports Activity Analytics" link="View all"/><div className="chart"><ResponsiveContainer><LineChart data={chart}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="m"/><YAxis/><Tooltip/><Line type="monotone" dataKey="p" stroke="#1678dc" strokeWidth={3}/><Line type="monotone" dataKey="e" stroke="#16b7aa" strokeWidth={3}/></LineChart></ResponsiveContainer></div></Card>
  <Card><PanelTitle title="Upcoming Activities" link="View all"/><div className="timeline">{events.map(e=><div key={e[0]}><i/><span><b>{e[0]}</b><small>Sports Center</small></span><time>{e[1]}<small>{e[2]}</small></time></div>)}</div></Card>
  <Card><PanelTitle title="Notifications" link="View all"/><div className="notifications">{['New funding request awaiting approval','Inventory item needs maintenance','Event report deadline tomorrow','Tournament event approved'].map((n,i)=><div key={n}><span className={`dot d${i}`}/><p>{n}<small>{i+2} hours ago</small></p></div>)}</div></Card>
  <Card><PanelTitle title="Inventory Overview"/><div className="pie-wrap"><ResponsiveContainer width="52%" height={150}><PieChart><Pie data={pie} dataKey="v" innerRadius={42} outerRadius={65}>{pie.map(x=><Cell key={x.c} fill={x.c}/>)}</Pie></PieChart></ResponsiveContainer><div className="pie-total"><b>482</b><small>Total Assets</small></div><ul><li>Available <b>318</b></li><li>Borrowed <b>98</b></li><li>Maintenance <b>42</b></li><li>Lost <b>24</b></li></ul></div></Card>
  <Card><PanelTitle title="Top Program PIC"/><ol className="leaderboard">{['Andi Pratama','Sarah Azzahra','Budi Santoso','Dwi Cahyo','Rina Marina'].map((x,i)=><li key={x}><span>{i+1}</span><i>{x.split(' ').map(y=>y[0]).join('').slice(0,2)}</i><b>{x}</b><small>{8-i} Programs</small><em>{95-i*4}%</em></li>)}</ol></Card>
  <Card><PanelTitle title="Quick Access"/><div className="quick"><button><Plus/>Create Program</button><button><CalendarDays/>Create Event</button><button><HandCoins/>Request Funds</button><button><PackageCheck/>Add Asset</button><button><FilePlus/>Create Report</button></div></Card>
 </div></>}
