import DataState from '../components/DataState';
import { useState } from 'react';
import { Plus, Search, FolderKanban, Activity, CheckCircle2 } from 'lucide-react';
import { PageTitle, StatCard, Card, Badge, Progress } from '../components/UI';
import { CollectionFeedback, CollectionEditor, Pagination, RowActions } from '../components/CollectionTools';
import { useCollection } from '../lib/collections';
import { useResource, money, date } from '../lib/hooks';
export default function Programs() {
  const c = useCollection('programs'); const stats = useResource('/dashboard');
  const [query, setQuery] = useState(''); const [status, setStatus] = useState('');
  const rows = c.rows.filter(row => row.name.toLowerCase().includes(query.toLowerCase()) && (!status || row.status === status));
  const summary = stats.loading || stats.error ? null : stats.data?.summary;
  return <><PageTitle title="Program kerja" subtitle="Jadwal, penanggung jawab, dan progres program departemen." action={c.manages && <button className="primary" onClick={() => c.setEditor({})}><Plus />Tambah program</button>} /><div className="mini-stats"><StatCard icon={<FolderKanban />} title="Total program" value={summary?.totalPrograms ?? '—'} /><StatCard icon={<Activity />} title="Program aktif" value={summary?.activePrograms ?? '—'} /><StatCard icon={<CheckCircle2 />} title="Selesai" value={summary?.completedPrograms ?? '—'} color="green" /></div><DataState loading={stats.loading} error={stats.error} retry={stats.reload} /><Card><div className="table-tools"><div className="search local"><Search /><input aria-label="Cari program" value={query} onChange={event => setQuery(event.target.value)} placeholder="Cari program di halaman ini…" /></div><select aria-label="Filter status program" value={status} onChange={event => setStatus(event.target.value)}><option value="">Semua status</option>{['Planning','Ongoing','Active','Completed','Cancelled'].map(value => <option key={value}>{value}</option>)}</select></div><CollectionFeedback collection={c} />{!c.loading && !c.error && c.rows.length > 0 && <div className="table-wrap"><table><thead><tr>{['Program','PIC','Tanggal','Status','Progres','Anggaran','Tindakan'].map(value => <th key={value}>{value}</th>)}</tr></thead><tbody>{rows.map(row => <tr key={row.id}><td><b>{row.name}</b><small>{row.description}</small></td><td>{row.pic}</td><td>{date(row.start_date)}–{date(row.end_date)}</td><td><Badge>{row.status}</Badge></td><td><div className="progress-cell"><Progress value={row.progress} /><span>{row.progress}%</span></div></td><td>{money(row.budget)}</td><td><RowActions collection={c} item={row} /></td></tr>)}</tbody></table>{!rows.length && <p className="data-state">Tidak ada hasil untuk filter ini.</p>}</div>}<Pagination collection={c} /></Card><CollectionEditor resource="programs" collection={c} /></>;
}
